language: php
php:
  - '7.0'
  - '7.1'

script:
   - composer install
   - vendor/bin/phpunit
   
notifications:
    email:
        recipients:
            - jeremy.durand@epsi.fr
            - jeremy.durand2449@gmail.com
        on_success: always
        on_failure: always
