language: php
php:
  - '7.0'
  - '7.1'

script:
   - composer install
   - vendor/bin/phpunit
   
 notifications:
    slack: 
    epsi-ic:Q5TUTkIv6U8rufTM3TFZk80J
    on_success: always
    on_failure: always
    on_error: always
    on_cancel: always
    
    email:
        recipients:
            - jeremy.durand@epsi.fr
            - jeremy.durand2449@gmail.com
        on_success: always
        on_failure: always
