language: php
php:
  - '7.0'
  - '7.1'

script:
   - composer install
   - vendor/bin/phpunit
   
notifications:
    email:
        recipients:
            - jeremy.durand@epsi.fr
        on_success: never
        on_failure: always
